name: Notify Google Chat on PR Events (Reusable)

on:
  workflow_call:
    inputs:
      header_image:
        description: "Custom header image URL (optional)"
        default: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        required: false
        type: string
      reply_mode:
        description: True for reply, false for a new message
        default: true
        required: false
        type: boolean
    secrets:
      google_chat_webhook:
        required: true

  pull_request:
    types: [opened, synchronize, reopened]

  pull_request_review:
    types: [submitted] 

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest
    steps:
      - name: Set input props
        id: set_inputs
        run: |
          echo "HEADER_IMAGE=${{ inputs.header_image }}" >> $GITHUB_ENV
          if [ ${{ inputs.reply_mode! }} ]; then
            REPLY_MODE="MESSAGE_REPLY_OPTION_UNSPECIFIED"
          else
            REPLY_MODE="REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD"
          fi
          echo "::set-output name=reply_mode::${REPLY_MODE}"

      - name: Prepare PR_EVENT message
        id: pr_event
        run: |
          if [ "${{ github.event_name }}" == "pull_request_review" ]; then
            PR_EVENT="${{ github.actor }} has submitted a review for the Pull Request"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_EVENT="${{ github.actor }} has opened/updated the Pull Request"
          fi
          echo "::set-output name=pr_event::${PR_EVENT}"

      - name: Send Notification to Google Chat on PR Events
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "cardsV2": [{
                  "cardId": "pr-notification",
                  "card": {
                    "header": {
                      "title": "GitHub Pull Request",
                      "subtitle": "${{ github.repository }}",
                      "imageUrl": "'"$HEADER_IMAGE"'"
                    },
                    "sections": [{
                      "widgets": [{
                        "textParagraph": {
                          "text": "<b>${{ github.actor }}</b> has triggered an event:<br><b>${{ github.event.pull_request.title }}</b><br>${{steps.pr_event.outputs.pr_event}}"
                        }
                      }]
                    },
                    {
                      "widgets": [{
                        "buttonList": {
                          "buttons": [{
                            "text": "View Pull Request",
                            "onClick": {
                              "openLink": {
                                "url": "${{ github.event.pull_request.html_url }}"
                              }
                            }
                          }]
                        }
                      }]
                    }]
                  }
                }],
                "thread": {
                  "threadKey": "${{ github.repository }}/${{ github.event.pull_request.number }}"
                }
              }' \
          "${{ secrets.google_chat_webhook }}&messageReplyOption=${{steps.set_inputs.outputs.reply_mode}}"
