name: Google Chat Webhook

on:
  workflow_call:
    secrets:
      google_chat_webhook:
        required: true

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "cardsV2": [{
                  "cardId": "pr-notification",
                  "card": {
                    "header": {
                      "title": "GitHub Pull Request",
                      "subtitle": "${{ github.repository }}",
                      "imageUrl": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                    },
                    "sections": [{
                      "widgets": [{
                        "textParagraph": {
                          "text": "**${{ github.actor }}** has **${{ github.event.action }}** a pull request: [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})"
                        }
                      }]
                    },
                    {
                      "widgets": [{
                        "buttons": [{
                          "textButton": {
                            "text": "View Pull Request",
                            "onClick": {
                              "openLink": {
                                "url": "${{ github.event.pull_request.html_url }}"
                              }
                            }
                          }
                        }]
                      }]
                    }]
                  }
                }]
              }' \
          "${{ secrets.google_chat_webhook }}"
