name: Google Chat Webhook

on:
  workflow_call:
    inputs:
      header_image:
        description: "Custom header image URL (optional)"
        default: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        required: false
        type: string
      reply_option:
        description: "new_thread or same_thread (optional, default same_thread)"
        default: 'same_thread'
        required: false
        type: string
    secrets:
      google_chat_webhook:
        required: true

  pull_request:
    types: [opened, synchronize, reopened]

  pull_request_review:
    types: [submitted] 

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest
    
    steps:
      - name: Prepare inputs
        id: prepare_inputs
        run: |
          echo "HEADER_IMAGE=${{ inputs.header_image }}" >> $GITHUB_ENV
          
          if [ "${{ inputs.reply_option }}" == "new_thread" ]; then
            echo "REPLY_OPTION=MESSAGE_REPLY_OPTION_UNSPECIFIED" >> $GITHUB_ENV
          else
            echo "REPLY_OPTION=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD" >> $GITHUB_ENV
          
